version: "3.9"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    env_file:
      - .env
  db:
    image: postgres:15.3-alpine3.18
    volumes:
      - db_data:/var/lib/postgresql/data
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 10s
      retries: 5
volumes:
  db_data:
