apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-updater-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: chat-cd
    namespace: default
roleRef:
  kind: Role
  name: deployment-updater
  apiGroup: rbac.authorization.k8s.io
