apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
  volumeName: chat-pv
