name: K8S pipeline
run-name: "K8S pipeline"
on: [push]
jobs:
  docker-image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: rolandsobczak/chat-api:${{ github.sha }}
  k8s-image-update:
    runs-on: ubuntu-latest
    needs: docker-image-build
    steps:
      - name: set up k8s
        uses: actions-hub/kubectl@master
        env:
          KUBE_HOST: ${{ secrets.KUBE_HOST }}
          KUBE_CERTIFICATE: ${{ secrets.KUBE_CERTIFICATE }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        with:
          args: set image deployments/chat-backend rolandsobczak/chat-api=rolandsobczak/chat-api:${{ github.sha }}
